### ISSUE TITLE
Just asking if its just angular position or more.

### ISSUE THREAD

**Issue by tugrul512bit** [TKJElectronics/KalmanFilter#28]
Does this filter take derivative of angle and second derivative of angle  into consideration? I guess its only angular position and angular velocity because the matrix is 2x2? If not, what kind of changes would be needed to add velocity & acceleration too?

**Comment by mindThomas** [comment]
You are correct, this the estimated states of this filter only includes position and thus it takes in angular velocity as an input to the propagation model.
By extending the state space to include velocity you would have a dynamic model which takes in angular acceleration. Do you have a sensor to measure that or what other idea would you have to drive the model?

**Comment by tugrul512bit** [comment]
I only have positional data but I can compute velocity & acceleration from backward-discrete-derivative approach (using just the position & timestep). Perhaps this can drive such a system (like with a bigger matrix of 3x3 or 4x4 idk). I'm completely new to this title.

Thank you very much for giving answer.

**Comment by mindThomas** [comment]
> backward-discrete-derivative approach (using just the position & timestep

Yes, that would just be the numerical derivative which would be very noisy. So there would not be much a model-based Kalman filter could do to improve this.

The Kalman filter can be designed to act as a low-pass filter on these numerical derivates to give you a smoothed velocity estimate, if that is what you are looking for? One way to do this is to design the model as a Constant-velocity model with only noise on the inputs. In this case your measurement vector would include both the position measurement and the angular velocity measurement.

**Comment by tugrul512bit** [comment]
My intention is just to filter noise from signal without delay. Many algorithms add delay either by computational steps requiring an output delay or just the computations themselves give a phase delay. To overcome this, prediction is required. Kalman can do this right? Maybe even with just angular position?

**Comment by mindThomas** [comment]
You are right. Both FIR and IIR filters will introduce a lag in real-time settings. If you don't need this at real-time (closed loop applications) you can do zero-phase filtering by running the filters forward and backward.

The Kalman filter in our case greatly reduces the lag for the angular position since it is model-based, driven by the derivative of the state to estimate, namely the angular velocity.
A Kalman filter can however not achieve zero lag since the Kalman Filter, using the estimated or tuned Measurement and Process Noises, balances between being very adaptive with short lag but a large error variance in steady state to being an aggressive smoother with long lag but a small error variance in steady state.

Since you want angular velocity without any delay you would need the derivative of this as a measured input.

**Comment by tugrul512bit** [comment]
Thank you for all the explanations. Have a nice day.
